# Connessione Oracle
quarkus.datasource.db-kind=oracle
quarkus.datasource.username=pocuser
quarkus.datasource.password=pocpass
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1

# Hibernate: crea/aggiorna lo schema da solo (SOLO per POC!)
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true