# Connessione Oracle
quarkus.datasource.db-kind=oracle
quarkus.datasource.username=pocuser
quarkus.datasource.password=pocpass
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@oracle-poc:1521/FREEPDB1

# Hibernate: crea/aggiorna lo schema da solo (SOLO per POC!)
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS